name: AdvancejoinConfig
main: advance\advancejoin\Core
version: 1.0.0
api: 4.0.0
author: KohakuChanX
description: "The AdvanceJoin Config Plugins for Minecraft Servers"
website: "plugin.nayukihub.tk"
